enum ScreenEnum {
	HOMESCREEN,
	LOADINGSCREEN,
	SELECTIONSCREEN,
	HELPSCREEN,
	GAMESCREEN,
	GAMEOVERSCREEN,
	WINSCREEN,
	CREDITSCREEN,
	PAUSESCREEN,
	SETTINGSSCREEN,
	MAPSELECTIONSCREEN,
	LOADGAMESCREEN
};